/**
 * PLL configuration — generated by gowin-pll for GW1NR-9 C6/I5
 * 27.000 MHz -> 99.000 MHz
 */
`ifndef SIMULATION
module gowin_pll_99(
        input  clock_in,
        output clock_out,
        output locked
    );

    rPLL #(
        .FCLKIN("27.0"),
        .IDIV_SEL(2),
        .FBDIV_SEL(10),
        .ODIV_SEL(8)
    ) pll (
        .CLKOUTP(), .CLKOUTD(), .CLKOUTD3(),
        .RESET(1'b0), .RESET_P(1'b0), .CLKFB(1'b0),
        .FBDSEL(6'b0), .IDSEL(6'b0), .ODSEL(6'b0),
        .PSDA(4'b0), .DUTYDA(4'b0), .FDLY(4'b0),
        .CLKIN(clock_in),
        .CLKOUT(clock_out),
        .LOCK(locked)
    );

endmodule
`endif
